name: hacktoberfestify

on:
  issues:
    types: [opened, closed]

jobs:
  hacktoberfestify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          issue: ${{ github.event.issue.number }}
